baseURL = 'https://sweetjuice.pages.dev/'
locale = 'en-us'
title = 'SweetJuice Docs'
theme = 'PaperMod' # renamed from hugo-PaperMod

[params]
ShowPostNavLinks = true

[outputs]
    home = ["HTML", "RSS", "JSON"]

[[menu.main]]
    name = "🔍 Search"
    url = "/search/"
    weight = 10

[[menu.main]]
    name = "Community"
    url = "https://github.com/sweet-juice/sweetjuice"
    weight = 20
